name: GitHub Actions 构造和部署 Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 第一步，获取源码，使用的是actions
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run-script build
    # 第二步，构建和部署，需要四个环境变量，分别为 GitHub 密钥、发布分支、构建成果所在目录、构建脚本
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh_pages
        FOLDER: build